### ISSUE TITLE
docker 搭建时出现错误

### ISSUE THREAD

**Issue by longchengguxiao** [Box-s-ville/luciabot#1]
首先在gocqhttp的dockerfile中最后一行需要添加“.exe”才可以运行
其次运行时会直接结束gocqhttp，返回错误 gocqhttp existed with code 1
暂时未找到解决方案，如果您有时间，还请查看一下

**Comment by cleoold** [comment]
你遇到的類似錯誤是這樣子的嗎？
```
ERROR: for gocqhttp  Cannot start service gocqhttp: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./go-cqhttp-v0.9.30": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```
這是因爲這個 repo 的文件權限沒有弄好，運行 `chmod 711 go-cqhttp-v0.9.30` 再 `docker-compose up` 就應該能運行了。或者去官網下載新的版本。
除此之外我還沒有遇到問題,包括你也不需要修改任何 dockerfile.
我是看到這個 issue 之後現場新開一個 Ubuntu 18.04 vm 測試的。

**Comment by cleoold** [comment]
嘿，請問這個問題還持續嗎

**Comment by longchengguxiao** [comment]
多謝關心，因為我不是在ubuntu上進行的測試（是在win10上），而且現時我發現我無法安裝ubuntu了，所以放弃了嘗試。不過最近在學習postgresql想要從這邊重新用gino繼續您文章上的步驟（文章現時已經看完了，一些功能已經實現了不過現時是用的txt文字儲存而不是資料庫）。您的文章是我的入門文章，作為一比特初學者，您的文章對我的啟發很大，感謝您的付出，祝生活順利！（不介意的話可以留一個聯繫方式嗎，比如郵箱或者QQ）

**Comment by cleoold** [comment]
> 
> 
> 多謝關心，因為我不是在ubuntu上進行的測試（是在win10上），而且現時我發現我無法安裝ubuntu了，所以放弃了嘗試。

在 Windows 上要下載 [以 .exe 結尾的文檔](https://github.com/Mrs4s/go-cqhttp/releases)。

>
>
> （不介意的話可以留一個聯繫方式嗎，比如郵箱或者QQ）

可以加QQ群 768887710
