### ISSUE TITLE
请问session.send的消息如何撤回

### ISSUE THREAD

**Issue by UtopiaXC** [Box-s-ville/luciabot#3]
你好，很抱歉打扰您
我查阅了文档，发现您提到的session.send方法和文档中的
message = await bot.send_group_msg(group_id = userGroup, message = content)
有一些出入，请问一下用session.send方法发出的消息如何获取message_id
麻烦了

**Comment by cleoold** [comment]
```py
    # 發送 5 秒后撤回
    ret = await session.send('message')
    if ret is not None:
        await asyncio.sleep(5)
        await session.bot.delete_msg(message_id=ret['message_id'])
```

不知道爲什麽 session.send 的簽名被 type 成了 None...

**Comment by UtopiaXC** [comment]
十分感谢，我去试一试
